server:
  port: 10014
spring:
  application:
    name: ManagerConsumer
  freemarker:
    suffix: .ftl
    template-loader-path:
    - classpath:/templates/
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10010/eureka